version: 0.2

env:
  variables:
    AWS_REGION: "us-west-1"
    REACT_APP_USERS_SERVICE_URL: "http://localhost:5001"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging in to ecr...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - bash build.sh
  post_build:
    commands:
      - bash post_build.sh
