version: 0.2

env:
  variables:
    AWS_REGION: "us-west-1"
    VITE_API_SERVICE_URL: "http://localhost:5004"

phases:
  pre_build:
    commands:
      - echo logging in to ecr...
      - >
        aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo building and testing dev images...
      - docker-compose up -d --build
      - docker-compose exec -T api python -m pytest "src/tests" -p no:warnings --cov="src"
      - docker-compose exec -T api flake8 src
      - docker-compose exec -T api black src --check
      - docker-compose exec -T api isort src --check-only
      - docker-compose exec -T client npm run lint
      - docker-compose exec -T client npm run prettier:check
      - docker-compose exec -T client npm run prettier:write
      - echo building prod images...
      - >
        docker build \
          -f services/users/Dockerfile.prod \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-users:prod \
          ./services/users
      - >
        docker build \
          -f services/client/Dockerfile.prod \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-client:prod \
          --build-arg NODE_ENV=production \
          --build-arg VITE_API_SERVICE_URL=$VITE_API_SERVICE_URL \
          ./services/client
  post_build:
    commands:
    - echo pushing prod images to ecr...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-users:prod
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-client:prod
