version: 0.2

env:
  variables:
    AWS_REGION: "us-west-1"
    REACT_APP_USERS_SERVICE_URL: "http://localhost:5001"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging in to ecr...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-users:prod || true
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-client:builder || true
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-client:prod || true
  build:
    commands:
      - echo building and testing dev images...
      - docker-compose up -d --build
      - docker-compose exec -T users pytest "project/tests" -p no:warnings --cov="project"
      - docker-compose exec -T users flake8 project
      - docker-compose exec -T users black project --check
      - docker-compose exec -T users /bin/sh -c "isort project/*/*.py" --check-only
      - docker-compose exec -T client npm run lint
      - docker-compose exec -T client npm run prettier:check
      - docker-compose exec -T client npm run prettier:write
      - echo building prod images...
      - >
        docker build \
          --cache-from $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-users:prod \
          -f services/users/Dockerfile.prod \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-users:prod \
          ./services/users
      - >
        docker build \
          --target builder \
          --cache-from $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-client:builder \
          -f services/client/Dockerfile.prod \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-client:builder \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_USERS_SERVICE_URL=$REACT_APP_USERS_SERVICE_URL \
          ./services/client
      - >
        docker build \
          --cache-from $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-client:prod \
          -f services/client/Dockerfile.prod \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-client:prod \
          ./services/client
  post_build:
    commands:
    - echo pushing prod images to ecr...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-users:prod
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-client:builder
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/test-driven-client:prod
